In [2]:
#Scrapping a website
import requests
from bs4 import BeautifulSoup

url = "https://arynews.tv/en/category/international-2/"
webpage = requests.get(url)

soup = BeautifulSoup(webpage.content,'html5lib')
#html_file = soup.prettify()

news_head = soup.find_all('a','href',)
new_desc = soup.find_all('p')
rows = soup.select('h2')
row = rows[0]
head = row.select('h1','topic-sec-item-head')

print(head)


ConnectionError: HTTPSConnectionPool(host='arynews.tv', port=443): Max retries exceeded with url: /en/category/international-2/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000A1B13DF198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

In [3]:
#Since i failed in scrapping so i created files through below file generator:

#File generator: will ask you for content of file 1 and will make te file and keep on making files untill you enter '0'

#Since i have created my 100 files ones, so i have commented it now!

#n = 1
#content ='1'
#while(content is not '0'):
    #file_name = "File" + str(n) + ".txt"
    #file = open(file_name,"w+")
    #print("Enter content of file",n,": ")
    #n+=1
    #content = input()
    #file.write(content)
    #file.close()
    

In [4]:

#I have made 100 files of news containg heading and description, separated by '*'
#But google classroom is not allowing to upload all the files so i have uploaded 1 pytohn filr and 19 text files

import numpy as np
Dictionary = dict() #dictionary of all unique words with their total repetition count in all files

i=1
total_no_of_files = 100
while i<=total_no_of_files:
    file = "File" + str(i) + ".txt"
    read_file=open(file)
    for line in read_file:
        words = line.split()
        for word in words:
            if word is not '*':
                if word[len(word)-1]=='.':
                    word = word[:len(word)-1]
                if word[len(word)-1]==':':
                    word = word[:len(word)-1]
                if word[len(word)-1]==',':
                    word = word[:len(word)-1]
                word = word.lower()
                if word not in Dictionary:
                    Dictionary[word]=1
                else:
                    Dictionary[word]+=1
    
    i+=1

print(Dictionary)


{'over': 15, 'a': 37, 'million': 3, 'protesters': 4, 'demand': 3, 'president’s': 1, 'resignation': 1, 'in': 86, 'chile': 2, 'more': 3, 'than': 2, 'one': 4, 'people': 4, 'took': 3, 'to': 93, 'the': 167, 'streets': 1, 'friday': 10, 'for': 32, 'largest': 1, 'protests': 4, 'week': 1, 'of': 90, 'deadly': 1, 'demonstrations': 2, 'demanding': 1, 'economic': 3, 'reforms': 2, 'majority': 2, '39': 3, 'uk': 4, 'truck': 8, 'victims': 1, 'likely': 1, 'from': 12, 'vietnam': 1, 'priest': 1, 'discovery': 3, 'bodies': 4, '-': 2, '38': 1, 'adults': 1, 'and': 31, 'teenager': 1, 'was': 10, 'made': 2, 'on': 63, 'wednesday': 3, 'after': 10, 'emergency': 3, 'services': 1, 'were': 9, 'alerted': 1, 'container': 3, 'an': 8, 'industrial': 2, 'site': 1, 'grays': 1, 'curfew': 2, 'continues': 4, '83rd': 3, 'consecutive': 3, 'day': 11, 'indian': 12, 'occupied': 11, 'kashmir': 20, 'kashmiris': 4, 'continue': 4, 'observe': 2, 'shutdown': 2, 'as': 14, 'silent': 2, 'protest': 5, 'against': 5, 'india’s': 4, 'recent': 2, 

In [5]:
counter =1
Number_to_word = dict()  #dictionary of unique words and their unique id
Word_to_number = dict()  #dictionary of unique ids and its corresponding word
for element in Dictionary:
    Number_to_word[counter] = element
    Word_to_number[element] = counter
    counter+=1
# Printing both the created dictioanries for confirmation:
print(Word_to_number)
print()    #One line space
print(Number_to_word)


{'over': 1, 'a': 2, 'million': 3, 'protesters': 4, 'demand': 5, 'president’s': 6, 'resignation': 7, 'in': 8, 'chile': 9, 'more': 10, 'than': 11, 'one': 12, 'people': 13, 'took': 14, 'to': 15, 'the': 16, 'streets': 17, 'friday': 18, 'for': 19, 'largest': 20, 'protests': 21, 'week': 22, 'of': 23, 'deadly': 24, 'demonstrations': 25, 'demanding': 26, 'economic': 27, 'reforms': 28, 'majority': 29, '39': 30, 'uk': 31, 'truck': 32, 'victims': 33, 'likely': 34, 'from': 35, 'vietnam': 36, 'priest': 37, 'discovery': 38, 'bodies': 39, '-': 40, '38': 41, 'adults': 42, 'and': 43, 'teenager': 44, 'was': 45, 'made': 46, 'on': 47, 'wednesday': 48, 'after': 49, 'emergency': 50, 'services': 51, 'were': 52, 'alerted': 53, 'container': 54, 'an': 55, 'industrial': 56, 'site': 57, 'grays': 58, 'curfew': 59, 'continues': 60, '83rd': 61, 'consecutive': 62, 'day': 63, 'indian': 64, 'occupied': 65, 'kashmir': 66, 'kashmiris': 67, 'continue': 68, 'observe': 69, 'shutdown': 70, 'as': 71, 'silent': 72, 'protest': 

In [6]:
#term document matrix
Term_document_matrix = np.zeros((100,len(Dictionary))) 
outer_count = 0

file = 1
while file<100:
    file_name = "File"+str(file)+".txt"
    readf = open(file_name,"r")
    for line in readf:
        words = line.split()
        for word in words:
            if(word is not '*'):
                if word[len(word)-1]=='.':
                    word = word[:len(word)-1]
                if word[len(word)-1]==':':
                    word = word[:len(word)-1]
                if word[len(word)-1]==',':
                    word = word[:len(word)-1]
                word = word.lower()
                col = Word_to_number[word]
                Term_document_matrix[file-1][col-1] = 1
            
    file+=1
print(Term_document_matrix)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:

# Getting user query:
query = input("Enter your query: ")
text = query.split(' ')
Query_matrix = np.zeros((1,len(Dictionary)))
for word in text:
    if word[len(word)-1]=='.':
        word = word[:len(word)-1]
    word = word.lower()
    if word in Dictionary:
        column = Word_to_number[word]
        Query_matrix[0][column-1] = 1
#query matrix is formed here from user query

#Resultant matrix is the result matrix of Query_matrix and Term_document_matrix:

Resultant_matrix = Query_matrix.dot(Term_document_matrix.transpose())

#Printing resultant matix for confirmation:
print(Resultant_matrix)

#Now finding the most relevant file:
n=0
count = 0
largest = 0
while n<100:
    if(Resultant_matrix[0][n-1]!=0):
        count+=1
        if(Resultant_matrix[0][n]>largest):
            largest = n
    n+=1
    
print("Total no. of relevent files: ",count)
print()     #one line space

print("Most relevant data: ")
file = open("File"+str(largest)+".txt")   #Opening most relevant file:
data = file.read()
lines = data.split('*')
for line in lines:
    print(line)
    


Enter your query: nawaz sharif
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 2. 0. 0. 0.
  0. 2. 1. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0.]]
Total no. of relevent files:  9

Most relevant data: 
Ailing Nawaz Sharif gets bail in Al-Azizia case on ‘medical grounds’ 
 A division bench of the IHC comprising Chief Justice Athar Minallah and Justice Mohsin Akhtar Kayani approved the bail of the PML-N supremo against two surety bonds of Rs1 million each


In [3]:
a = np.zeros((5,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
